name: samples_index
description: A visual index of Flutter samples
homepage: https://github.com/flutter/samples/tree/main/web/samples_index
version: 0.0.1

environment:
  sdk: ^3.0.0

dependencies:
  json_annotation: ^4.8.1
  path: ^1.8.3
  yaml: ^3.1.2
  mdc_web: ^0.6.0
  # ^2.1.5 is no longer compatible with our overridden sass version
  # https://github.com/flutter/samples/issues/1472
  sass_builder: 2.1.4
  checked_yaml: ^2.0.3
  webdriver: ^3.0.2
  html: ^0.15.3

dev_dependencies:
  grinder: ^0.9.4
  flutter_lints: ^2.0.1
  test: ^1.24.2
  json_serializable: ^6.6.2
  build: ^2.4.0
  build_runner: ^2.4.2
  build_web_compilers: ^4.0.3
  image: ">=3.2.0 <5.0.0"

# waiting for the next material-components-web release.
# Once released, it will need to be rolled into package:mdc_web.
#
# https://github.com/material-components/material-components-web/pull/7158
# https://github.com/flutter/samples/issues/1472
dependency_overrides:
  sass: 1.32.10