name: github_dataviz

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  http: ^0.13.4

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  assets:
    - preview.png
    - github_data/
